### ISSUE TITLE
List of what is currently being blocked

### ISSUE THREAD

**Issue by Zethson** [marklindhout/hetzblocker#1]
Hey,

thanks for the extension. Is there a list somewhere to see what sites/media outlets are currently blocked?

**Comment by marklindhout** [comment]
Howdy!

Great that you like the extension :)

Indeed, there's two lists the extension uses for blocking. The first one is the domain list, found at src/js/common/domainlist.js, and the second one is a list with full url's for blocking specific pages within a domain (e.g. YouTube channels, Twitter accounts), which can be found at src/js/common/pagelist.js

I hope that helps. If not, let me know, and I'll create some sort of documentation page which lists all the block domains and urls on the project's GitHub page.
