### ISSUE TITLE
wordpress.com being completely blocked

### ISSUE THREAD

**Issue by sophyx** [marklindhout/hetzblocker#9]
wordpress.com is getting completely blocked even though only certain pages should be blocked with a subdomain (according to the pagelist)

**Comment by marklindhout** [comment]
Hi @sophyx,

Thanks for reporting this. I see this behaviour as well. I traced it to an error in matching for the page block list. Right now, the subdomain is not compared, which leads to all `*.wordpress.com` domains being blocked.

I am already working on a fix in the branch `add_unit_tests`, that will be merged over the next week, and I will then also update the extensions on the web stores, of course.

**Comment by marklindhout** [comment]
This issue was fixed in release v0.7.2, which you can find on the Firefox and Chrome web stores, and here on GitHub at: https://github.com/marklindhout/hetzblocker/releases/tag/v0.7.2
